server.port=8080
spring.datasource.url=jdbc:sqlite:../data/ghostblock.sqlite
spring.datasource.driver-class-name=org.sqlite.JDBC

ghostblock.scanner.binary=../scanner-core/target/release/ghost-block-cli
ghostblock.scanner.default-image=../data/sample.img
ghostblock.scanner.default-db=../data/ghostblock.sqlite